In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Analyzing the Impact of Weather on Delhi's Air Quality

## 1. Introduction and Problem Formulation
Delhi, the capital territory of India, consistently ranks among the most polluted cities globally. High concentrations of particulate matter (PM2.5 and PM10) pose a severe public health crisis, leading to respiratory and cardiovascular emergencies. 

While the *sources* of this pollution are well-documented (vehicular emissions, crop stubble burning, construction dust), **meteorological conditions** are the primary catalyst for severe smog events. Factors like wind speed, humidity, and temperature inversions dictate whether pollutants disperse into the upper atmosphere or become trapped at ground level.

### Project Objectives and Scope
This technical report explores the intersection of meteorology and urban pollution. To ensure a good analysis, this project uses **two independent data sources**:
1. **Air Quality Data:** Historical daily readings of pollutants and AQI from the Central Pollution Control Board (CPCB).
2. **Historical Weather Data:** Meteorological metrics including temperature, humidity, and wind speed.

**Our primary goals are to:**
1. Ingest, clean, and chronologically merge these two disparate datasets.
2. Perform Data Analysis to uncover statistical correlations between weather phenomena and hazardous AQI spikes.
3. Build a predictive data model to forecast air quality risks based on impending weather conditions.

In [4]:
# Load datasets
df_air_all_cities = pd.read_csv('../data/air_quality.csv')
df_weather = pd.read_csv('../data/delhi_weather.csv')

# We only want Delhi data to match our weather dataset
df_air = df_air_all_cities[df_air_all_cities['City'] == 'Delhi'].copy()

# Verify successful loading
print(f"Air Quality Data (Delhi only) Shape: {df_air.shape}")
print(f"Weather Data Shape: {df_weather.shape}\n")

print("--- First 3 rows of Air Quality Data ---")
display(df_air.head(3))

print("\n--- First 3 rows of Weather Data ---")
display(df_weather.head(3))

Air Quality Data (Delhi only) Shape: (2009, 16)
Weather Data Shape: (96432, 25)

--- First 3 rows of Air Quality Data ---

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
10229,Delhi,2015-01-01,313.22,607.98,69.16,36.39,110.59,33.85,15.20,9.25,41.68,14.36,24.86,9.84,472.0,Severe
10230,Delhi,2015-01-02,186.18,269.55,62.09,32.87,88.14,31.83,9.54,6.65,29.97,10.55,20.09,4.29,454.0,Severe
10231,Delhi,2015-01-03,87.18,131.90,25.73,30.31,47.95,69.55,10.61,2.65,19.71,3.91,10.23,1.99,143.0,Moderate

--- First 3 rows of Weather Data ---

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex.1,moon_illumination,moonrise,moonset,...,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
0,2009-01-01 00:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,14,19,0,50,0.0,1016,10,10,331,12
1,2009-01-01 01:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,13,21,0,51,0.0,1016,10,10,329,13
2,2009-01-01 02:00:00,22,9,0.0,8.7,4,1,31,10:11 AM,09:57 PM,...,12,22,0,52,0.0,1016,9,10,327,13